gazebo_ros_control:
  pid_gains:
    arm_joint1: {p: 20.0, d: 1.0, i: 0.01, i_clamp: 1}
    arm_joint2: {p: 10.0, d: 0.5, i: 0.01, i_clamp: 1}
    arm_joint3: {p: 5.0, d: 0.2, i: 0.01, i_clamp: 1}
    arm_joint4: {p: 1.0, d: 0.1, i: 0.01, i_clamp: 1}
    arm_joint5: {p: 0.5, d: 0.01, i: 0.01, i_clamp: 1}
