# MoveIt-specific simulation settings
moveit_sim_hw_interface:
    joint_model_group: arm
    joint_model_group_pose: init_pose
# Settings for ros_control control loop
generic_hw_control_loop:
    loop_hz: 300
    cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
    joints:
        - arm_joint1
        - arm_joint2
        - arm_joint3
        - arm_joint4
        - arm_joint5
    sim_control_mode: 0

red/manipulator: 
        joint_state_controller:
            type: joint_state_controller/JointStateController
            publish_rate: 50

        arm_controller:
            type: position_controllers/JointTrajectoryController
            joints:
                - arm_joint1
                - arm_joint2
                - arm_joint3
                - arm_joint4
                - arm_joint5
            constraints:
                goal_time: 2.0
                state_publish_rate: 25

controller_list:
    - name: red/manipulator/arm_controller
      action_ns: follow_joint_trajectory
      type: FollowJointTrajectory
      default: true
      joints: 
        - arm_joint1 
        - arm_joint2
        - arm_joint3
        - arm_joint4
        - arm_joint5
